version: '2'
services:
  db:
    container_name: 'db'
    build: './db'
    image: db
    ports:
      - "5430:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  web:
    container_name: 'web'
    build: './web'
    image: web
    ports:
      - "8080:8080"
    depends_on:
      - db
  consul:
    container_name: consul
    command: "-node myconsul -bootstrap -data-dir=/consul/data/"
    image: gliderlabs/consul-server
    volumes:
     - ./consul/config:/consul/config
     - ./consul/data:/consul/data
    ports:
     - "53:9600/udp"
     - "8088:8500"
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: 'registrator'
    volumes:
     - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
     - consul
